version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medtracker
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase:4.30.0
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources:/db/changelog
    working_dir: /db
    command:
      - --changeLogFile=changelog/db/changelog/changelog.sql
      - --url=jdbc:postgresql://postgres:5432/medtracker
      - --username=postgres
      - --password=postgres
      - update